### PR TITLE
JENKINS-54846: RAW HTML is shown in cron column since 2.138.2

### PR DESCRIPTION
**Pull request by bguerin**

### CODE REVIEW

**Comment by daniel-beck** [comment]
Before:

before

After:

after

---

While I'm not the maintainer of the plugin, I will not hesitate to blacklist any plugin that deliberately bypasses protection mechanisms this way.

**Comment by bguerin** [comment]
@daniel-beck Fixed, thanks !

**Comment by sfarbota** [comment]
Is there any plan to merge this PR and include in a future release? What are the next steps?

**Review by MarkEWaite — APPROVED** [review]

**Comment by sfarbota** [comment]
Awesome, thanks @MarkEWaite ! Love to see an old issue getting resolved. This will fix a long-standing eye sore in my team's Jenkins instance.

**Pull request merged**
